image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          # TODO - REMOVE `cd web` from all following steps when using in your app
          - cd web && npm install
          - cd web && npm run validate --if-present
